--- 
#TAreas para actualizacion de paquetes
#- hosts: all				
#  become: true				 
#  pre_tasks:				

#  - name: Install Updates  (CentOS)
#    tags: always
#    yum:
#      name: "*"
#      state: latest
#    when: ansible_distribution == "CentOS"

#  - name: Install Updates (Ubuntu)
#    tags: always
#    apt:
#      upgrade: dist
#    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks: 

  - name: install apache2 package Ubuntu	 
    tags: apache,apache2,ubuntu
    apt:				 
      name: 
        - apache2
        - libapache2-mod-php		
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache2 package CentOS       
    tags: apache,centos,httpd
    yum:                                
      name: 
        - httpd
        - php                       
      state: latest
    when: ansible_distribution == "CentOS"

  - name: Copy default Html for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks: 

  - name: Install MariaDB package (CentOS)
    tags: centos,db,mariadb
    yum:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

  - name: INstall mariadb package (Ubuntu)
    tags: db,mariadb,ubuntu   
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba    #En ubuntu y CentOS el paquete tiene el mismo nombre por lo que no hay problemas al hacer estpo
      state: latest
 
